import { LectureDocument, CommuteNote } from '../../types';
import saveAs from 'file-saver';

export function generateMarkdownStudyGuide(document: LectureDocument, notes: CommuteNote[]): string {
  const docNotes = notes.filter(n => n.documentId === document.id);
  const actionNotes = docNotes.filter(n => n.category === 'action');
  const conceptNotes = docNotes.filter(n => n.category === 'concept');
  const examNotes = docNotes.filter(n => n.category === 'exam');

  const lines: string[] = [
    `# 🎓 Commute Study Guide: ${document.title}`,
    `*Generated by The Student's Companion on ${new Date().toLocaleDateString()}*`,
    `*Total Audio Runtime: ~${document.durationMinutes} Minutes | Source: ${document.originalName}*`,
    '',
    '---',
    '',
    '## 📑 Executive Summary & Chapter Breakdown',
    ''
  ];

  document.segments.forEach((seg, idx) => {
    lines.push(`### Chapter ${idx + 1}: ${seg.title}`);
    lines.push(`⏱️ *Estimated Listen Time: ~${Math.round(seg.estimatedSeconds / 60)} min*`);
    lines.push('');
    if (seg.keyPoints && seg.keyPoints.length > 0) {
      lines.push('**Key Takeaways:**');
      seg.keyPoints.forEach(kp => lines.push(`- ${kp}`));
      lines.push('');
    }
    lines.push(`> **Audio Narrative:** ${seg.synthesizedAudioText}`);
    lines.push('');
  });

  lines.push('---');
  lines.push('');
  lines.push('## 🎙️ Commute Dictation Notes & AI Synthesis');
  lines.push('');

  if (examNotes.length > 0) {
    lines.push('### 🚩 Critical Exam Flags & Midterm Alerts');
    examNotes.forEach(n => {
      lines.push(`- **[${n.timestampFormatted}]** ${n.synthesizedContent}`);
      lines.push(`  *Spoken Thought:* _"${n.rawTranscription}"_`);
    });
    lines.push('');
  }

  if (actionNotes.length > 0) {
    lines.push('### ⚡ Action Items & Assignment Checklist');
    actionNotes.forEach(n => {
      lines.push(`- [ ] **[${n.timestampFormatted}]** ${n.synthesizedContent}`);
    });
    lines.push('');
  }

  if (conceptNotes.length > 0) {
    lines.push('### 💡 Key Concept Definitions & Formulations');
    conceptNotes.forEach(n => {
      lines.push(`- **[${n.timestampFormatted}]** ${n.synthesizedContent}`);
    });
    lines.push('');
  }

  if (docNotes.length === 0) {
    lines.push('_No voice notes recorded during this commute session._');
  }

  return lines.join('\n');
}

export function downloadMarkdownFile(document: LectureDocument, notes: CommuteNote[]) {
  const content = generateMarkdownStudyGuide(document, notes);
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const filename = `${document.title.replace(/[^a-zA-Z0-9_-]/g, '_')}_Study_Guide.md`;
  saveAs(blob, filename);
}
